import { LoginButton } from "@/features/loginButton/LoginButton"
import { FC, ReactNode } from "react"
import Head from 'next/head';

interface MainLayoutProps {
    children: ReactNode
}

const MainLayout: FC<MainLayoutProps> = ({children}) => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name='description' content='Generated by create-t3-app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <nav className='sticky top-0 bg-white z-40 border-b'>
                <div className='flex justify-end max-w-7xl mx-auto py-2'>
                    <LoginButton />                    
                </div>
            </nav>  
            <main className='max-w-7xl mx-auto pt-10'>
                {children}
            </main>
        </>
    )
}

export {
    MainLayout
}