-- AlterTable
ALTER TABLE "TestTemplate" ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "startDate" DROP NOT NULL,
ALTER COLUMN "endDate" DROP NOT NULL,
ALTER COLUMN "durationTime" DROP NOT NULL;
